import os

class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv("CALENDAR_DATABASE_URL")

    KEYCLOAK_URL = os.getenv("KEYCLOAK_URL")
    KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM")
    KEYCLOAK_CLIENT_ID = os.getenv("KEYCLOAK_CLIENT_ID")

    PROFILE_SERVICE_URL = os.getenv("PROFILE_SERVICE_URL")